package model.dao;
// Generated 2011.04.06. 10:37:37 by Hibernate Tools 3.2.1.GA



/**
 * House generated by hbm2java
 */
public class House  implements java.io.Serializable {


     private Integer id;
     private int ownerid;
     private int size;
     private int worth;

    public House() {
    }

    public House(int ownerid, int size, int worth) {
       this.ownerid = ownerid;
       this.size = size;
       this.worth = worth;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(int ownerid) {
        this.ownerid = ownerid;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public int getWorth() {
        return this.worth;
    }
    
    public void setWorth(int worth) {
        this.worth = worth;
    }




}


