package model.dao;
// Generated 2011.04.06. 10:37:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private int money;
     private String role;
     private Date dateofreg;
     private String fullname;
     private String email;

    public User() {
    }

	
    public User(String username, String password, int money, String role, String email) {
        this.username = username;
        this.password = password;
        this.money = money;
        this.role = role;
        this.email = email;
    }
    public User(String username, String password, int money, String role, Date dateofreg, String fullname, String email) {
       this.username = username;
       this.password = password;
       this.money = money;
       this.role = role;
       this.dateofreg = dateofreg;
       this.fullname = fullname;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getMoney() {
        return this.money;
    }
    
    public void setMoney(int money) {
        this.money = money;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Date getDateofreg() {
        return this.dateofreg;
    }
    
    public void setDateofreg(Date dateofreg) {
        this.dateofreg = dateofreg;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


